### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by Mesyme** [cryptopunksnotdead/punks.starter#2]
hi, sorry to bother you, but i don't know anything about ruby.
It gives me this error:

```
C:\Users\M\Downloads\punks.starter-master>ruby no1/generate.rb
pixelart/0.2.2 on Ruby 3.0.2 (2021-07-07) [x64-mingw32] in (C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pixelart-0.2.2)
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/parser_std.rb:116:in `parse': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:172:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:203:in `to_a'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:203:in `read'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:54:in `block in read'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:33:in `open'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/csvreader-1.2.4/lib/csvreader/reader_hash.rb:49:in `read'
        from C:/Users/M/Downloads/punks.starter-master/generate.rb:8:in `read_csv'
        from no1/generate.rb:10:in `<main>'
```

**Comment by geraldb** [comment]
Please, post your ruby scripting support questions to <https://old.reddit.com/r/CryptoPunksDev/>.  I try my best to help out.
